### PR TITLE
update to mdx-deck v3

### PR DESCRIPTION
**Pull request by mhartington**

### CODE REVIEW

**Comment by mhartington** [comment]
Looks like this fails in node 8 because it doesn't have `Array.flat`

**Comment by pomber** [comment]
Thanks!
Does the basic example works for you?   
I run `yarn start` at the root and `yarn start` at `examples/basic/` and I get this error:

```
ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve 'code-surfer' in 'code-surfer/node_modules/mdx-deck/.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir'

File: .cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/846c704b0f4025149460ab83d1b558fc.js
```

**Comment by mhartington** [comment]
Odd, getting this as well. Nothing seems out of place, though I'm wondering if mdx-deck move to go all in on gatsby is the cause. @jxnblk Could you shed some light here?

**Comment by pomber** [comment]
It's probably related to the example using the `.bin` from a parent folder in the [start script](https://github.com/pomber/code-surfer/blob/code-surfer-v2/examples/basic/package.json#L10).  
I don't remember why I'm not using `mdx-deck` as a dependency in the example's package.json. That would allow us to use the script `"start": "mdx-deck deck.mdx"` which should fix the problem.

**Comment by mhartington** [comment]
So I think that plus the `"code-surfer": "link:../.."` is the cause. When replacing mdx-deck with a hard dep, the, it ends up still trying to resolve things at the root level. 

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (4:48)

File: ../../../../node_modules/gatsby-theme-mdx-deck/src/index.js:4:48


Error: Command failed with exit code 1 (EPERM): gatsby develop --host localhost --port 8000 --open
    at makeError (/Users/mhartington/GitHub/code-surfer/examples/basic/node_modules/mdx-deck/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/mhartington/GitHub/code-surfer/examples/basic/node_modules/mdx-deck/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mhartington** [comment]
Well making some progress, though now in an infinite loop with update

```
react-dom.development.js:56 Uncaught Invariant Violation: Maximum update depth exceeded. 
This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. 
React limits the number of nested updates to prevent infinite loops.
```

**Comment by mhartington** [comment]
without diving in too much, I think the animation context is the problematic part. Though I have no idea why that would be as the update itself doesn't even touch it

**Comment by pomber** [comment]
> without diving in too much, I think the animation context is the problematic part. Though I have no idea why that would be as the update itself doesn't even touch it

Yes, that's strange. In theory, the code inside the `standalone` folder shouldn't be affected.

I haven't checked mdx-deck v3 yet, I'll probably take a look next week.

**Comment by mhartington** [comment]
Alright, so digging further, it seems the `useDimensions` hook is causing the issue, specifically [this call](https://github.com/pomber/code-surfer/blob/code-surfer-v2/src/standalone/dimensions.ts#L37-L60) but because of it being calling in `useLayoutEffect`. Seems it's causing the infinite loop

**Comment by pomber** [comment]
Thanks @mhartington 
I may take a look this weekend. Let me know if you made more progress.

**Comment by pomber** [comment]
Seems like the infinite loop is caused by `useNotes`. But there are many problems caused by mdx-deck re-mounting the slide for every render. I sent a PR to fix it: jxnblk/mdx-deck#428

I have a few more fixes, I'll update this PR after we have a new version of mdx-deck.

**Pull request merged**
